latency-wait: 60
keep-going: True
printshellcmds: True
rerun-incomplete: True

use-envmodules: True
use-conda: True

# Cluster submission
jobname: "{rulename}.{jobid}"
drmaa: " -V -cwd -j y -o ./log -pe serial {resources.threads} -l mfree={resources.mem}G -l h_rt={resources.hrs}:00:00 -w n -S /bin/bash"

# Job resources
default-resources:
 - mem=2
 - threads=1
 - hrs=4
